### ISSUE TITLE
The main Solution explorer name has changed to "Solution Explorer 0"

### ISSUE THREAD

**Issue by noam-honig** [stickleprojects/NamedSolutionExplorer#7]
![image](https://user-images.githubusercontent.com/16635859/39987015-2abef992-576c-11e8-86b3-eb307113fe79.png)

I guess it's residue of the demo it's based on

**Comment by stickleprojects** [comment]
The solution explorer needs to be uniquely named fro me to be able to differentiate it from the one i just created :(
I could rename it back if that would be acceptable?
